version: 2.1

workflows:
  test:
    jobs:
      - build-run-linux:
          context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: master
    jobs:
    - build-run-linux:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an SDK key and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-linux:
    docker:
      - image: mozilla/sbt
    steps:
      - checkout
      - run:
          name: insert SDK key and flag key into demo code
          command: |
            sed -i.bak "s/sdkKey *= *\".*\"/sdkKey = \"${LD_HELLO_WORLD_SDK_KEY}\"/" src/main/scala/Hello.scala
            sed -i.bak "s/featureFlagKey *= *\".*\"/featureFlagKey = \"${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}\"/" src/main/scala/Hello.scala
      - run:
          name: build demo
          command: sbt compile
      - run:
          name: run demo
          command: |
            sbt run | tee output.txt
            grep "is true for this user" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)
